"""adding default to column status of table suggestions

Revision ID: 06da260547b4
Revises: 1e8d0c515cfa
Create Date: 2025-07-10 02:31:19.834889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06da260547b4'
down_revision = '1e8d0c515cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
