"""making password_hash column in table users nullable

Revision ID: 1449d8da29e2
Revises: 29121d0c11d6
Create Date: 2025-08-05 04:14:46.832200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1449d8da29e2'
down_revision = '29121d0c11d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
