"""Make rhymeScheme_id in poems not nullable

Revision ID: 1482588747ee
Revises: fe417d49ff8b
Create Date: 2025-07-02 20:41:41.115109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1482588747ee'
down_revision = 'fe417d49ff8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.alter_column('rhymeScheme_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.alter_column('rhymeScheme_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
