"""Adding unique constraint poem_id/verse_id/rougeMetric_id to table rougeScores

Revision ID: 152429795a0f
Revises: be41ac6f2622
Create Date: 2025-08-01 03:10:00.253595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152429795a0f'
down_revision = 'be41ac6f2622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rougeScores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_rougeScores_poem_verse_metric', ['poem_id', 'verse_id', 'rougeMetric_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rougeScores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rougeScores_poem_verse_metric', type_='unique')

    # ### end Alembic commands ###
