"""Adding table for poem statuses + FK on the status column of the Poem class

Revision ID: 1a0a75890216
Revises: ace93a9edc48
Create Date: 2025-07-15 03:29:17.086907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0a75890216'
down_revision = 'ace93a9edc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poemStatuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poemStatus', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_poemStatuses')
    )
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_poems_poemStatuses_id', 'poemStatuses', ['status'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_poems_poemStatuses_id', type_='foreignkey')

    op.drop_table('poemStatuses')
    # ### end Alembic commands ###
