"""Adding table suggestionBatches and table suggestions

Revision ID: 1e8d0c515cfa
Revises: 1482588747ee
Create Date: 2025-07-10 01:14:43.230616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8d0c515cfa'
down_revision = '1482588747ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestionBatches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('batchNo', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], name='fk_suggestionBatches_verse_id'),
    sa.PrimaryKeyConstraint('id', name='pk_suggestionBatches')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suggestionBatch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('suggestion', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['suggestionBatch_id'], ['suggestionBatches.id'], name='fk_suggestions_suggestionBatches_id'),
    sa.PrimaryKeyConstraint('id', name='pk_suggestions')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    op.drop_table('suggestionBatches')
    # ### end Alembic commands ###
