"""Dropping relationship from ActionTargetTypes

Revision ID: 2244b3dfc9f3
Revises: c4cc9f1cb708
Create Date: 2025-06-21 21:20:33.130438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2244b3dfc9f3'
down_revision = 'c4cc9f1cb708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
