"""add statusNo column to poemStatues

Revision ID: 2af4c65181fa
Revises: 1a0a75890216
Create Date: 2025-07-15 04:13:57.461235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af4c65181fa'
down_revision = '1a0a75890216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poemStatuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poemStatusNo', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_poemStatuses_poemStatusNo', ['poemStatusNo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poemStatuses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_poemStatuses_poemStatusNo', type_='unique')
        batch_op.drop_column('poemStatusNo')

    # ### end Alembic commands ###
