"""Initial schema

Revision ID: 3caa7387f7c5
Revises: 
Create Date: 2025-06-19 12:03:47.316396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3caa7387f7c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionTypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actionType', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actionType', name='uq_actions_action')
    )
    op.create_table('configurationCategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('configurationCategory', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_configurationCategories')
    )
    op.create_table('poemLanguages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_poemLanguages')
    )
    op.create_table('rhymeSchemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rhymeScheme', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_rhymeSchemes')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nmfDim', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_themes')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actionType_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actionType_id'], ['actionTypes.id'], name='fk_actions_action_type'),
    sa.PrimaryKeyConstraint('id', name='pk_actions')
    )
    op.create_table('configurationParameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poemLanguage_id', sa.Integer(), nullable=False),
    sa.Column('configurationCategory_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['configurationCategory_id'], ['configurationCategories.id'], name='fk_configurationParameters_category_id'),
    sa.ForeignKeyConstraint(['poemLanguage_id'], ['poemLanguages.id'], name='fk_configurationParameters_poemLanguage_id'),
    sa.PrimaryKeyConstraint('id', name='pk_configurationParameters'),
    sa.UniqueConstraint('poemLanguage_id', 'configurationCategory_id', 'parameter', name='uq_actions_poemLanguage_category_parameter')
    )
    op.create_table('rhymeSchemeElements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rhymeScheme_id', sa.Integer(), nullable=False),
    sa.Column('poemLanguage_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('rhymeSchemeElement', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['poemLanguage_id'], ['poemLanguages.id'], name='fk_rhymeSchemeElements_poemLanguage_id'),
    sa.ForeignKeyConstraint(['rhymeScheme_id'], ['rhymeSchemes.id'], name='fk_rhymeSchemeElements_rhymeScheme_id'),
    sa.PrimaryKeyConstraint('id', name='pk_rhymeSchemeElements')
    )
    op.create_table('themeDescriptors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('poemLanguage_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('descriptor', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['poemLanguage_id'], ['poemLanguages.id'], name='fk_theme_descriptors_pomeLangugage_id'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name='fk_theme_descriptors_theme_id'),
    sa.PrimaryKeyConstraint('id', name='pk_themeDescriptors')
    )
    op.create_table('poems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poemLanguage_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='fk_poems_action_id'),
    sa.ForeignKeyConstraint(['poemLanguage_id'], ['poemLanguages.id'], name='fk_poems_poemLanguage_id'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name='fk_poems_theme_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_poems_user_id'),
    sa.PrimaryKeyConstraint('id', name='pk_poems')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poem_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], name='fk_keywords_poem_id'),
    sa.PrimaryKeyConstraint('id', name='pk_keywords')
    )
    op.create_table('stanzas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poem_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='fk_stanzas_action_id'),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], name='fk_stanzas_poem_id'),
    sa.PrimaryKeyConstraint('id', name='pk_stanzas')
    )
    op.create_table('verses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stanza_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('verse', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='fk_verses_action_id'),
    sa.ForeignKeyConstraint(['stanza_id'], ['stanzas.id'], name='fk_verses_stanza_id'),
    sa.PrimaryKeyConstraint('id', name='pk_verses')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verses')
    op.drop_table('stanzas')
    op.drop_table('keywords')
    op.drop_table('poems')
    op.drop_table('themeDescriptors')
    op.drop_table('rhymeSchemeElements')
    op.drop_table('configurationParameters')
    op.drop_table('actions')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('rhymeSchemes')
    op.drop_table('poemLanguages')
    op.drop_table('configurationCategories')
    op.drop_table('actionTypes')
    # ### end Alembic commands ###
