"""Changing actionTargetDescription into actionTargetTypeDescription in ActionTargetTypes

Revision ID: 4467243a6de9
Revises: 2244b3dfc9f3
Create Date: 2025-06-21 21:31:23.738260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4467243a6de9'
down_revision = '2244b3dfc9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actionTargetTypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actionTargetTypeDescription', sa.String(length=1000), nullable=False))
        batch_op.drop_column('actionTargetDescription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actionTargetTypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actionTargetDescription', sa.VARCHAR(length=1000), nullable=False))
        batch_op.drop_column('actionTargetTypeDescription')

    # ### end Alembic commands ###
