"""Adding column max_n to table RougeMetric

Revision ID: 5c28ff88d622
Revises: a7890754e0bf
Create Date: 2025-07-17 02:47:00.987182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c28ff88d622'
down_revision = 'a7890754e0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rougeMetrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_n', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rougeMetrics', schema=None) as batch_op:
        batch_op.drop_column('max_n')

    # ### end Alembic commands ###
