"""Adding group_id column to acions table

Revision ID: 5db1cf42f6bb
Revises: 2af4c65181fa
Create Date: 2025-07-16 19:44:29.112172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db1cf42f6bb'
down_revision = '2af4c65181fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_actions_actions_group_id', 'actions', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_actions_actions_group_id', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
