"""Adding a label to language and persistence to rhymescheme

Revision ID: 79a835037d4d
Revises: cf26a54abf5e
Create Date: 2025-06-26 16:00:24.803308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a835037d4d'
down_revision = 'cf26a54abf5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poemLanguages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=False))

    with op.batch_alter_table('rhymeSchemes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persistent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rhymeSchemes', schema=None) as batch_op:
        batch_op.drop_column('persistent')

    with op.batch_alter_table('poemLanguages', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
