"""Adding column theme_id to table keywordSuggestionCollections

Revision ID: 80a20086e95c
Revises: f7ee81fad344
Create Date: 2025-07-22 03:05:02.968019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a20086e95c'
down_revision = 'f7ee81fad344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywordSuggestionCollections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_keywordCollections_themes_id', 'themes', ['theme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywordSuggestionCollections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_keywordCollections_themes_id', type_='foreignkey')
        batch_op.drop_column('theme_id')

    # ### end Alembic commands ###
