"""Adding distanceMetrics and distanceScores tables

Revision ID: 84b36ac67c84
Revises: 5c28ff88d622
Create Date: 2025-07-17 13:34:58.033264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b36ac67c84'
down_revision = '5c28ff88d622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distanceMetrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distance_metric', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_distanceMetrics')
    )
    op.create_table('distanceScores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poem_id', sa.Integer(), nullable=True),
    sa.Column('verse_id', sa.Integer(), nullable=True),
    sa.Column('distance_metric_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['distance_metric_id'], ['distanceMetrics.id'], name='fk_distanceScores_distanceMetrics_id'),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], name='fk_distanceScores_poems_id'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], name='fk_distanceScores_verses_id'),
    sa.PrimaryKeyConstraint('id', name='pk_distanceScores')
    )
    with op.batch_alter_table('rougeMetrics', schema=None) as batch_op:
        batch_op.drop_column('max_n')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rougeMetrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_n', sa.INTEGER(), nullable=True))

    op.drop_table('distanceScores')
    op.drop_table('distanceMetrics')
    # ### end Alembic commands ###
