"""Adapt poems, action for logging, add actiontarget and actiontargettype make classes single instead of plural

Revision ID: 8a44bdf70155
Revises: b78d7c21be15
Create Date: 2025-06-21 20:59:14.237169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a44bdf70155'
down_revision = 'b78d7c21be15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionTargetTypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actionTargetType', sa.String(length=100), nullable=False),
    sa.Column('actionTargetDescription', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_actionTargetTypes'),
    sa.UniqueConstraint('actionTargetType', name='uq_actiontargettpyes_actiontargettype')
    )
    op.create_table('actionTargets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('actionTargetType_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actionTargetType_id'], ['actionTargetTypes.id'], ),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='fk_actionTargets_actions_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actionTypes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_actions_action'), type_='unique')
        batch_op.create_unique_constraint('uq_actiontypes_actiontype', ['actionType'])

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('actionType_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('actionType_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('actionTypes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_actiontypes_actiontype', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_actions_action'), ['actionType'])

    op.drop_table('actionTargets')
    op.drop_table('actionTargetTypes')
    # ### end Alembic commands ###
