"""Rename themeDescriptors column descriptor to themeDescriptor

Revision ID: 99b57de8fc70
Revises: 785e646968be
Create Date: 2025-06-21 01:53:10.813076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b57de8fc70'
down_revision = '785e646968be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('themeDescriptors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('themeDescriptor', sa.String(length=100), nullable=False))
        batch_op.drop_column('descriptor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('themeDescriptors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptor', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('themeDescriptor')

    # ### end Alembic commands ###
