"""Initial schema

Revision ID: 99c36cb4ba3b
Revises: 
Create Date: 2025-06-18 20:21:26.570023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c36cb4ba3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action', name='uq_actions_action')
    )
    op.create_table('poemLanguages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rhymeSchemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rhymeScheme', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nmfDim', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poemLanguage_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['action'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['poemLanguage_id'], ['poemLanguages.id'], ),
    sa.ForeignKeyConstraint(['theme'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rhymeSchemeElements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rhymeScheme_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('rhymeSchemeElement', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['rhymeScheme_id'], ['rhymeSchemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themeDescriptors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('descriptor', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poem_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stanzas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poem_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stanza_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('verse', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['action'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['stanza_id'], ['stanzas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verses')
    op.drop_table('stanzas')
    op.drop_table('keywords')
    op.drop_table('themeDescriptors')
    op.drop_table('rhymeSchemeElements')
    op.drop_table('poems')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('rhymeSchemes')
    op.drop_table('poemLanguages')
    op.drop_table('actions')
    # ### end Alembic commands ###
