"""Adding tables rougeMetrics and rougeScores

Revision ID: a7890754e0bf
Revises: 5db1cf42f6bb
Create Date: 2025-07-17 00:34:39.522095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7890754e0bf'
down_revision = '5db1cf42f6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rougeMetrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rouge_metric', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_rougeMetrics')
    )
    op.create_table('rougeScores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poem_id', sa.Integer(), nullable=True),
    sa.Column('verse_id', sa.Integer(), nullable=True),
    sa.Column('rougeMetric_id', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], name='fk_rougeScores_poems_id'),
    sa.ForeignKeyConstraint(['rougeMetric_id'], ['rougeMetrics.id'], name='fk_rougeScores_rougeMetrics_id'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], name='fk_rougeScores_verses_id'),
    sa.PrimaryKeyConstraint('id', name='pk_rougeScores')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rougeScores')
    op.drop_table('rougeMetrics')
    # ### end Alembic commands ###
