"""Adding table previousPoems for changes to the poem-records)

Revision ID: ace93a9edc48
Revises: 9e6a7152c55d
Create Date: 2025-07-15 02:14:43.598133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace93a9edc48'
down_revision = '9e6a7152c55d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previousPoems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poem_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('previousTitle', sa.String(length=500), nullable=True),
    sa.Column('previousRhymeScheme_id', sa.Integer(), nullable=False),
    sa.Column('previousTheme_id', sa.Integer(), nullable=False),
    sa.Column('previousStatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='fk_previousPoems_actions_id'),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], name='fk_previousPoems_poems_id'),
    sa.ForeignKeyConstraint(['previousRhymeScheme_id'], ['rhymeSchemes.id'], name='fk_previousPoems_rhymeSchemes_id'),
    sa.ForeignKeyConstraint(['previousTheme_id'], ['themes.id'], name='fk_previousPoems_themes_id'),
    sa.PrimaryKeyConstraint('id', name='pk_previousPoems')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previousPoems')
    # ### end Alembic commands ###
