"""Add actionTypeDescription to actionTypes

Revision ID: b78d7c21be15
Revises: 99b57de8fc70
Create Date: 2025-06-21 13:44:27.738400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78d7c21be15'
down_revision = '99b57de8fc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actionTypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actionTypeDescription', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actionTypes', schema=None) as batch_op:
        batch_op.drop_column('actionTypeDescription')

    # ### end Alembic commands ###
