"""Adding columns lookupKey and poemText to table poems

Revision ID: be41ac6f2622
Revises: 348de5fb62da
Create Date: 2025-07-27 20:50:30.974574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be41ac6f2622'
down_revision = '348de5fb62da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lookupKey', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('poemText', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_poems_user_lookupKey', ['user_id', 'lookupKey'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.drop_constraint('uq_poems_user_lookupKey', type_='unique')
        batch_op.drop_column('poemText')
        batch_op.drop_column('lookupKey')

    # ### end Alembic commands ###
