"""Adapt naming unnamed constraints

Revision ID: c4cc9f1cb708
Revises: 8a44bdf70155
Create Date: 2025-06-21 21:15:31.091138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cc9f1cb708'
down_revision = '8a44bdf70155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
