"""Adding table previousKeywords

Revision ID: cc0196dd8863
Revises: cf1cbad6bc9d
Create Date: 2025-07-20 04:20:44.151330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0196dd8863'
down_revision = 'cf1cbad6bc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previousKeywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('previousKeyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='fk_previousKeywords_actions_id'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name='fk_previousKeywords_keywords_id'),
    sa.PrimaryKeyConstraint('id', name='pk_previousKeywords')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previousKeywords')
    # ### end Alembic commands ###
