"""Adding tables keywordSuggestionBatches, keywordSuggestionCollections, keywordSuggestions

Revision ID: cf1cbad6bc9d
Revises: f0cdad9fc0af
Create Date: 2025-07-19 19:25:28.176632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1cbad6bc9d'
down_revision = 'f0cdad9fc0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywordSuggestionBatches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('batchNo', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name='fk_keywordSuggestionBatches_keywords_id'),
    sa.PrimaryKeyConstraint('id', name='pk_keywordSuggestionBatches')
    )
    op.create_table('keywordSuggestionCollections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keywordSuggestionBatch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keywordSuggestionBatch_id'], ['keywordSuggestionBatches.id'], name='fk_keywordCollections_keywordSuggestionBatches_id'),
    sa.PrimaryKeyConstraint('id', name='pk_keywordCollections')
    )
    op.create_table('keywordSuggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keywordSuggestionCollection_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('suggestion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['keywordSuggestionCollection_id'], ['keywordSuggestionCollections.id'], name='fk_keywordSuggestions_keywordSuggestionCollections_id'),
    sa.PrimaryKeyConstraint('id', name='pk_keywordSuggestions')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywordSuggestions')
    op.drop_table('keywordSuggestionCollections')
    op.drop_table('keywordSuggestionBatches')
    # ### end Alembic commands ###
