"""Removing action_id from Poem, Stanza and Verse

Revision ID: cf26a54abf5e
Revises: 4467243a6de9
Create Date: 2025-06-22 03:22:03.830781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf26a54abf5e'
down_revision = '4467243a6de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_poems_actions_id'), type_='foreignkey')
        batch_op.drop_column('action_id')

    with op.batch_alter_table('stanzas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stanzas_actions_id'), type_='foreignkey')
        batch_op.drop_column('action_id')

    with op.batch_alter_table('verses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_verses_actions_id'), type_='foreignkey')
        batch_op.drop_column('action_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_verses_actions_id'), 'actions', ['action_id'], ['id'])

    with op.batch_alter_table('stanzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_stanzas_actions_id'), 'actions', ['action_id'], ['id'])

    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_poems_actions_id'), 'actions', ['action_id'], ['id'])

    # ### end Alembic commands ###
