"""Changing distance_mectric_id column into distanceMetric_id in table distanceScores

Revision ID: f0cdad9fc0af
Revises: 84b36ac67c84
Create Date: 2025-07-17 16:16:41.781115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0cdad9fc0af'
down_revision = '84b36ac67c84'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('distanceScores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distanceMetric_id', sa.Integer(), nullable=False))
        # Don't drop the old constraint if it doesn't exist
        # batch_op.drop_constraint('fk_distanceScores_distanceMetrics_id', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_distanceScores_distanceMetrics_id',
            'distanceMetrics',
            ['distanceMetric_id'],
            ['id']
        )
        batch_op.drop_column('distance_metric_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distanceScores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_metric_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_distanceScores_distanceMetrics_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'distanceMetrics', ['distance_metric_id'], ['id'])
        batch_op.drop_column('distanceMetric_id')

    # ### end Alembic commands ###
