"""Adding column keyword_id to table keywordSuggestions

Revision ID: f7ee81fad344
Revises: cc0196dd8863
Create Date: 2025-07-20 14:38:02.108744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ee81fad344'
down_revision = 'cc0196dd8863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywordSuggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_keywordSuggestions_keywords_id', 'keywords', ['keyword_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywordSuggestions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_keywordSuggestions_keywords_id', type_='foreignkey')
        batch_op.drop_column('keyword_id')

    # ### end Alembic commands ###
