"""Add rhymeScheme_id to poems

Revision ID: fe417d49ff8b
Revises: 79a835037d4d
Create Date: 2025-07-02 19:27:30.688342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe417d49ff8b'
down_revision = '79a835037d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rhymeScheme_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_poems_rhymeSchemes_id', 'rhymeSchemes', ['rhymeScheme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_poems_rhymeSchemes_id', type_='foreignkey')
        batch_op.drop_column('rhymeScheme_id')

    # ### end Alembic commands ###
